# cloudbuild.yaml
# Substitutions you should set in the trigger or override in manual builds
substitutions:
  _REPO: cloud-run-repo
  _REGION: us-central1
  _PIPELINE: cloudrun-pipeline
  _DEPLOY_REGION: us-central1

steps:
  - id: 'Build image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/cloudrun-sample:$SHORT_SHA', '.']

  - id: 'Push image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/cloudrun-sample:$SHORT_SHA']

  - id: 'Create Cloud Deploy release'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        IMAGE=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/cloudrun-sample:$SHORT_SHA
        RELEASE=rel-${SHORT_SHA}
        gcloud deploy releases create ${RELEASE} \
          --delivery-pipeline=${_PIPELINE} \
          --region=${_DEPLOY_REGION} \
          --images=cloudrun-sample=${IMAGE} \
          --project=$PROJECT_ID

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/cloudrun-sample:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
