apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloudrun-app-pipeline
description: Cloud Deploy pipeline for Cloud Run app
serialPipeline:
  stages:
  - targetId: dev
    profiles: [dev]
  - targetId: qa
    profiles: [qa]
  - targetId: prod
    profiles: [prod]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Dev environment
run:
  location: asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa
description: QA environment
run:
  location: asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Prod environment
run:
  location: asia-south1
