steps:
# Step 1: Docker Build and Push
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build', '-t',
      'asia-south1-docker.pkg.dev/mythic-beanbag-463309-e9/deploy-to-cloudrun/cloudrun-app:${_BUILD_ID}',
      '.'
    ]
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'asia-south1-docker.pkg.dev/mythic-beanbag-463309-e9/deploy-to-cloudrun/cloudrun-app:${_BUILD_ID}'
    ]

# Step 2: Apply Cloud Deploy configuration
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'gcloud'
  args:
    [
      'deploy', 'apply',
      '--file=clouddeploy.yaml',
      '--region=asia-south1',
      '--project=mythic-beanbag-463309-e9'
    ]

# Step 3: Wait to ensure target propagation
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
    - -c
    - |
      echo "Waiting for Cloud Deploy targets to propagate..."
      sleep 60

# Step 4: Trigger Release
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'gcloud'
  args:
    [
      'deploy', 'releases', 'create', '${_BUILD_ID}',
      '--delivery-pipeline', 'cloudrun-app-pipeline',
      '--region', 'asia-south1',
      '--images', 'app=asia-south1-docker.pkg.dev/mythic-beanbag-463309-e9/deploy-to-cloudrun/cloudrun-app:${_BUILD_ID}',
      '--project=mythic-beanbag-463309-e9'
    ]

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _BUILD_ID: rel-20250625-002
