# cloudbuild.yaml
# Cloud Build config: build Docker image, push to Artifact Registry, apply Cloud Deploy, and trigger release

substitutions:
  _BUILD_ID: rel-${SHORT_SHA}        # Build/Release identifier

steps:
  # Step 1: Docker Build and Push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build', '-t',
        'asia-south1-docker.pkg.dev/clear-booking-470907-q6/cloud-run-repo/cloudrun-sample:${_BUILD_ID}',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-south1-docker.pkg.dev/clear-booking-470907-q6/cloud-run-repo/cloudrun-sample:${_BUILD_ID}'
      ]

  # Step 2: Apply Cloud Deploy configuration
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      [
        'deploy', 'apply',
        '--file=clouddeploy.yaml',
        '--region=asia-south1',
        '--project=clear-booking-470907-q6'
      ]

  # Step 3: Wait to ensure target propagation
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Waiting for Cloud Deploy targets to propagate..."
        sleep 60

  # Step 4: Trigger Release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      [
        'deploy', 'releases', 'create', '${_BUILD_ID}',
        '--delivery-pipeline', 'cloudrun-pipeline',
        '--region', 'asia-south1',
        '--images', 'cloudrun-sample=asia-south1-docker.pkg.dev/clear-booking-470907-q6/cloud-run-repo/cloudrun-sample:${_BUILD_ID}',
        '--project', 'clear-booking-470907-q6'
      ]

options:
  logging: CLOUD_LOGGING_ONLY
