# clouddeploy.yaml - Delivery pipeline + Targets + Automation
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloudrun-pipeline
description: Delivery pipeline dev -> qa -> prod
serialPipeline:
  stages:
    - targetId: dev
      profiles: [dev]
    - targetId: qa
      profiles: [qa]
    - targetId: prod
      profiles: [prod]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Development Cloud Run target
run:
  location: projects/PROJECT_ID/locations/REGION
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa
description: QA Cloud Run target
run:
  location: projects/PROJECT_ID/locations/REGION
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Production Cloud Run target (requires manual approval)
requireApproval: true
run:
  location: projects/PROJECT_ID/locations/REGION
---
# Automation: automatically promote from dev -> qa when dev rollout succeeds
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: cloudrun-pipeline/auto-promote-to-qa
description: Automatically promote dev -> qa after successful dev rollout
suspended: false
serviceAccount: automation-sa@PROJECT_ID.iam.gserviceaccount.com
selector:
  targets:
    - id: qa
rules:
  - promoteReleaseRule:
      name: "promote-to-qa"
      source: "dev"
