steps:
  # Step 1: Apply Cloud Deploy configuration
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud deploy apply \
          --file=cloudeploy.yaml \
          --region=asia-south1 \
          --project=mythic-beanbag-463309-e9

  # Step 2: Download Skaffold (v2.16.1)
  - name: 'gcr.io/cloud-builders/curl'
    id: download-skaffold
    args:
      [
        "-L",
        "https://storage.googleapis.com/skaffold/releases/v2.16.1/skaffold-linux-amd64",
        "-o",
        "/workspace/skaffold"
      ]

  # ✅ Step 3: Deploy using Skaffold with verbose debug output
  - name: 'ubuntu'
    id: deploy-with-skaffold
    entrypoint: bash
    args:
      - '-c'
      - |
        apt-get update && \
        apt-get install -y ca-certificates && \
        chmod +x /workspace/skaffold && \
        /workspace/skaffold run \
          --verbosity=debug \
          --default-repo=asia-south1-docker.pkg.dev/mythic-beanbag-463309-e9/deploy-to-cloudrun

options:
  logging: CLOUD_LOGGING_ONLY
