apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloudrun-app-pipeline
description: Cloud Run pipeline with automation

serialPipeline:
  stages:
    - targetId: dev
      profiles: [dev]
    - targetId: qa
      profiles: [qa]
    - targetId: prod
      profiles: [prod]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Cloud Run dev environment
run:
  location: projects/clear-booking-470907-q6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa
description: Cloud Run qa environment
run:
  location: projects/clear-booking-470907-q6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Cloud Run prod environment
run:
  location: projects/clear-booking-470907-q6/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: cloudrun-app-pipeline/promote-dev-to-qa
description: Auto promote from dev → qa
suspended: false
serviceAccount: 326372984052-compute@developer.gserviceaccount.com
selector:
  targets:
  - id: dev
rules:
- promoteReleaseRule:
    name: auto-promote-to-qa
    wait: 1m
    toTargetId: qa
---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: cloudrun-app-pipeline/promote-qa-to-prod
description: Auto promote from qa → prod
suspended: false
serviceAccount: 326372984052-compute@developer.gserviceaccount.com
selector:
  targets:
  - id: qa
rules:
- promoteReleaseRule:
    name: auto-promote-to-prod
    wait: 1m
    toTargetId: prod
