# deploy-qa.yaml - Cloud Run service definition for QA
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudrun-sample-qa
  labels:
    env: qa
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
    spec:
      containers:
        - image: cloudrun-sample
          env:
            - name: ENV
              value: "qa"
          ports:
            - containerPort: 8080
