# deploy-dev.yaml - Cloud Run service definition for DEV
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudrun-sample-dev
  labels:
    env: dev
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
    spec:
      containers:
        - image: cloudrun-sample
          env:
            - name: ENV
              value: "dev"
          ports:
            - containerPort: 8080
