apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-app-prod
spec:
  template:
    spec:
      containers:
      - image: my-app-image
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
