apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: cloudrun-app
build:
  artifacts:
    - image: asia-south1-docker.pkg.dev/mythic-beanbag-463309-e9/deploy-to-cloudrun/cloudrun-app
  tagPolicy:
    sha256: {}
  googleCloudBuild:
    projectId: mythic-beanbag-463309-e9
deploy:
  cloudRun:
    projectId: mythic-beanbag-463309-e9
    region: asia-south1
    serviceName: cloudrun-app
    allowUnauthenticated: true
