apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: cloud-run-app

build:
  artifacts:
    - image: us-central1-docker.pkg.dev/clear-booking-470907-q6/cloud-run-repo/cloudrun-app

profiles:
- name: dev
  deploy:
    cloudrun:
      projectid: clear-booking-470907-q6
      region: us-central1
      service: cloudrun-sample-dev

- name: qa
  deploy:
    cloudrun:
      projectid: clear-booking-470907-q6
      region: us-central1
      service: cloudrun-sample-qa

- name: prod
  deploy:
    cloudrun:
      projectid: clear-booking-470907-q6
      region: us-central1
      service: cloudrun-sample-prod
